In [4]:
import torch
import torch.nn as nn

device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [10]:
list1 = [torch.rand(4) for _ in range(4)]
list1

[tensor([0.9692, 0.0347, 0.2280, 0.0031]),
 tensor([0.4170, 0.5498, 0.3099, 0.6067]),
 tensor([0.9656, 0.5872, 0.3816, 0.6392]),
 tensor([0.7008, 0.5423, 0.3386, 0.3897])]

In [11]:
torch.stack(torchlist1)

tensor([[0.9692, 0.0347, 0.2280, 0.0031],
        [0.4170, 0.5498, 0.3099, 0.6067],
        [0.9656, 0.5872, 0.3816, 0.6392],
        [0.7008, 0.5423, 0.3386, 0.3897]])