In [15]:
import torch
import torch.nn as nn

import matplotlib.pyplot as plt
import seaborn as sns

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

data = torch.tensor([[0, 1, 0],
                     [1, 0, 1],
                     [1, 1, 1],
                     [0, 0, 0],
                     [1, 1, 0]]).unsqueeze(0).float().to(device)

targets = torch.tensor([1, 2, 3, 4, 5]).unsqueeze(0).unsqueeze(2).float().to(device)

linear1 = nn.Linear(3, 3).to(device)
relu = nn.ReLU().to(device)
linear2 = nn.Linear(3, 3).to(device)

optimizer = torch.optim.AdamW(list(linear1.parameters()) + list(linear2.parameters()), lr=0.01)

loss_f = nn.MSELoss()

epochs = 10

for epoch in range(epochs):
    combined = linear1(data)
    activated = relu(combined)
    combined = linear2(activated)
    
    a, b, c = combined.split(1, dim=2)
    
    print(linear1.weight.data)
    
    loss = loss_f(a, targets)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

combined = linear1(data)
activated = relu(combined)
combined = linear2(activated)
a, b, c = combined.split(1, dim=2)
print(a.cpu())


tensor([[ 0.0472,  0.3354,  0.1332],
        [-0.2747,  0.0169, -0.3277],
        [ 0.3937, -0.4912,  0.1194]], device='cuda:0')
tensor([[ 0.0372,  0.3254,  0.1232],
        [-0.2747,  0.0269, -0.3276],
        [ 0.3937, -0.4911,  0.1194]], device='cuda:0')
tensor([[ 0.0272,  0.3154,  0.1132],
        [-0.2746,  0.0369, -0.3276],
        [ 0.3936, -0.4911,  0.1194]], device='cuda:0')
tensor([[ 0.0172,  0.3054,  0.1033],
        [-0.2746,  0.0469, -0.3276],
        [ 0.3936, -0.4911,  0.1194]], device='cuda:0')
tensor([[ 0.0073,  0.2954,  0.0933],
        [-0.2746,  0.0569, -0.3275],
        [ 0.3936, -0.4910,  0.1194]], device='cuda:0')
tensor([[-0.0026,  0.2855,  0.0834],
        [-0.2746,  0.0669, -0.3275],
        [ 0.3935, -0.4910,  0.1194]], device='cuda:0')
tensor([[-0.0124,  0.2756,  0.0736],
        [-0.2745,  0.0768, -0.3275],
        [ 0.3935, -0.4909,  0.1194]], device='cuda:0')
tensor([[-0.0222,  0.2659,  0.0638],
        [-0.2745,  0.0868, -0.3275],
        [ 0.3934, -0.49