In [1]:
import torch
import torch.nn as nn

In [7]:
    T = 32
    
    positions = torch.arange(T).unsqueeze(0)  # ensure positions tensor is on the same device as input x
    qk_distances = positions.unsqueeze(-1) - positions.unsqueeze(-2)  # shape: (1, T, T)
    
    qk_distances

tensor([[[  0,  -1,  -2,  ..., -29, -30, -31],
         [  1,   0,  -1,  ..., -28, -29, -30],
         [  2,   1,   0,  ..., -27, -28, -29],
         ...,
         [ 29,  28,  27,  ...,   0,  -1,  -2],
         [ 30,  29,  28,  ...,   1,   0,  -1],
         [ 31,  30,  29,  ...,   2,   1,   0]]])

In [32]:
positions = torch.arange(10)
positions

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
positions = torch.arange(10).unsqueeze(0)
positions = positions.unsqueeze(-1)
print(positions.shape)
positions

torch.Size([1, 10, 1])


tensor([[[0],
         [1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]])

In [22]:
# positions.shape
positions.unsqueeze().shape

torch.Size([1, 1, 10])